services:

  postgres-db:
    image: postgres:15-alpine
    container_name: messenger_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-network
      - frontend-network
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: messenger_redis
    ports:
      - "6379:6379"
    networks:
      - data-network
      - frontend-network

  app:
    build: .
    container_name: messenger_app
    command: uvicorn src.secure_messenger.main:app --host 0.0.0.0 --port 8000
    networks:
      - data-network
      - backend-network
    depends_on:
      - postgres-db
      - redis
    volumes:
      - ./src:/src
    env_file:
      - .env

  nginx:
    image: nginx:stable-alpine
    container_name: messenger_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  data-network:
    driver: bridge
    internal: true
  backend-network:
    driver: bridge
    internal: true
  frontend-network:
    driver: bridge
